---
layout: default
title: 예외처리
parent: Java Basic
nav_order: 9
---

# 예외처리

---

## 예외처리

- 프로그램의 오류는 발생시저에 따라 컴파일 에러, 런타임 에러, 논리적 에러가 있다.
- 에러(error): 발생하면 복구할 수 없는 심각한 오류를 말한다. 메모리 부족, 스택 오버 플로우 등이 있다.
- 예외(exception): 프로그래머가 적절한 코드를 통해 대비할 수 있는 오류를 말한다. 클래스 형변환 실패, 파일 읽기 실패 등이 있다.
- 예외처리: 예외 발생 시 프로그램의 비정상 종료를 막고 실행항태를 유지하는 것으로 예외의 감지 및 예외 발생 시 동작할 코드로 이루어진다.

## 예외의 계열\_RuntimeException/Unchecked_Exception/checked

|       |  Object   |                  |
| :---: | :-------: | :--------------: |
|       | Throwable |
| Error | Exception | RuntimeException |

#### RuntimeException/Unchecked

- 런타임 시점에 확인된다.
- 명시적으로 예외처리 하지 않더라도 컴파일은 된다. 하지만 런타임 과정에 예외가 발생한다.
- 프로그래머의 실수나 논리 오류로 발생한다.
- 직접 try catch로 처리하거나 최상위 호출자에서 throws한다.(중간 호출자에게 위임하는 것도 가능)

#### Exception/checked

- 컴파일 시점에 확인된다.
- 명시적으로 예외처리 하지않으면 컴파일 에러가 발생한다.
- 외부환경과 상호작용, I/O 작업 등 예측 가능한 예외상황을 다룰 때 사용된다.
- 일반적으로 throws하고 try catch로 직접 처리하는 경우는 적다.
- throws를 사용하여 예외를 발생시킨 메서드는 호출한 메소드에게 위임해야 한다.(중간 호출자에게 위임하는 것도 가능)

```java
package Err;

public class Checked_Unchecked {
	public static void method1() throws ClassNotFoundException {
		Class.forName("SSAFY");
	}

	public static void method2() throws ClassNotFoundException {
		method1();
	}

	public static void method3() {
		int i = 1 / 0;
	}

	public static void method4() {
		method3();
	}

	public static void main(String[] args) {
//		method2(); // checked 예외는 대처 코드가 없으면 컴파일 되지 않는다.
		method4(); // unchecked 예외는 대처 코드가 없어도 컴파일은 된다.
		// checked
		try {
			method2();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		// unchecked
		try {
			method4();
		} catch (ArithmeticException e) {
			e.printStackTrace();
		}
	}
}
```

## 상속관계에서 예외처리

- 메서드 재정의 할 때 상위 클래스가 던지는 예외보다 더 상위 예외를 던질 수 없다.

```java
import java.io.FileNotFoundException;
import java.io.IOException;

class Parent {
	public void methodA() throws IOException {
	}

	public void methodB() throws ClassNotFoundException {
	}
}

public class 상속관계 extends Parent {
	@Override
	public void methodA() throws FileNotFoundException {
	}

//	@Override
//	public void methodB() throws Exception {
//	}
	// 부모가 던지는 예외보다 더 큰 예외(부모)를 자식이 더질 수 없음.
	public static void main(String[] args) {
		int[] nums = { 10 };

		try {
			System.out.println(nums[1]);
			int n = 0;
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("크기를 벗어나 버렸습니다_Array");
		} catch (Exception e) {
			System.out.println("크기를 벗어나 버렸습니다_Exception");
		}
		System.out.println("프로그램 종료");
	}
	// catch문에 무관한 예외를 넣으면 컴파일 에러가 발생한다.
	// catch문에 예외범위는 작은것(하위)에서 큰것(상위) 순서로 적어야 한다.
	// Exception은 다른 예외 처리의 조상이기 때문에 다형성에 따라 다른 예외를 처리할 수 있다.
}
```

## 사용자 정의 예외

- 사용자가 직접 예외를 작성할 수 있다.
- Exception, RuntimeException 클래스를 상속받아 작성한다.
- throw 키워드를 사용하여 처리한다.

```java
class FruitNotFoundException extends Exception {
	public FruitNotFoundException(String name) {
		super(name + "에 해당하는 과일은 없습니다.");
	}
}

public class 사용자정의 {
	public static String[] fruits = { "사과", "오렌지", "토마토" };

	public static void getFruits(String name) throws FruitNotFoundException {
		for (int i = 0; i < fruits.length; i++) {
			if (name.equals(fruits[i])) {
				fruits[i] = null;
				return;
			}
		}
		// 사용자 정의 예외를 발생시킬 때는 throw 키워드를 사용해야 한다.
		throw new FruitNotFoundException(name);
	}

	public static void main(String[] args) {
		try {
			getFruits("사과");
			getFruits("바나나"); // 존재하지 않는 과일을 호출
		} catch (FruitNotFoundException e) {
			e.printStackTrace();
		}
	}
}
```

## finally 키워드

- finally 키워드 안에 있는 내용은 finally키워드 앞에서 정상 실행되거나, 예외가 처리되거나, 예외가 미처리되거나, 리턴문이 있어도 항상 실행된다.

```java
public class Finally {
	public static void main(String[] args) {
		// 정상 실행 1245
		// 예외 발생 1345
		// 예외 미처리 14
		// try문에 return이 들어가는 경우 124
		// catch문에 return이 들어가는 경우 134

//		int num = 1; // 정상 실행
		int num = 0; // 예외 발생
		int[] nums = { 1 };
		try {
			System.out.println("1");
			int i = 1 / num;
//			nums[2] = 10; // 예외 미처리
			System.out.println("2");
//			return; // try 문에 return이 들어가는 경우
		} catch (ArithmeticException e) {
			System.out.println("3");
			return; // catch 문에 return이 들어가는 경우
		} finally {
			System.out.println("4");
		}
		System.out.println("5");
	}
}
```
